### ISSUE TITLE
dealing with punctuations in sentance

### ISSUE THREAD

**Issue by amirroozbeh** [shbz80/wasp-piglatin#8]

**Comment by rufoliveira** [comment]
I have noticed this during my tests, and thought that it degrades a lot the Product performance.
When running the program with: 

> Is Rui a pig?

the piggified version becomes:

> Isway uiRay away ig?pay

This is unnacceptable for our high demanding users.

I added a temporary fix, in which we simply ignore the punctuation marks, so that:

> Is Rui a pig?

becomes

> Is Rui a pig

and then the piggified version becomes:

> Isway uiRay away igpay

This is a temporary fix done with commit 0e897a1cc22d36375254d704eaaeaf6d108f847a, this issue still remains to be fixed.

**Comment by amirroozbeh** [comment]
Now the punctuation is been handled as : 

If it is at end of any world we are excluding it from piggyfing but still keeping it at end result. example : 
Is amir a pig?

becomes

Isway amirway away igpay?
 
If the word has more than 2 punctuation or the punctuation is not at the end we are not translating it and just send it as it is to out put. 

example : 
Pig??  and p?ig 

we might consider the case such as "it's" to be translated . I'll arise issue to fix it.
